import type { Task, TimeEntry } from "./types";
export const minutesLabel=(minutes:number)=>minutes<60?`${minutes}m`:`${Math.floor(minutes/60)}h ${minutes%60?`${minutes%60}m`:""}`.trim();
export const secondsLabel=(seconds:number)=>{const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60),s=Math.max(0,Math.floor(seconds%60));return h?`${h}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`:`${m}:${String(s).padStart(2,"0")}`};
export function taskSeconds(taskId:string,entries:TimeEntry[],now=Date.now()){return entries.filter(e=>e.taskId===taskId).reduce((sum,e)=>sum+(e.stoppedAt?e.durationSeconds:Math.max(0,Math.floor((now-new Date(e.startedAt).getTime())/1000))),0)}
export const dueTone=(task:Task,now=new Date())=>{if(task.status==="done"||!task.dueDate)return "neutral";const days=(new Date(`${task.dueDate}T23:59:59`).getTime()-now.getTime())/86400000;return days<0?"overdue":days<3?"soon":"neutral"};
export function monthGrid(anchor:Date){const first=new Date(anchor.getFullYear(),anchor.getMonth(),1),start=new Date(first);start.setDate(first.getDate()-first.getDay());return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})}

const dayMs=86_400_000;
export const localDateKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const validDateKey=(value:string|undefined)=>/^\d{4}-\d{2}-\d{2}$/.test(value??"")&&!Number.isNaN(new Date(`${value}T00:00:00`).getTime());
const dateFromKey=(value:string)=>new Date(`${value}T00:00:00`);
const addLocalDays=(date:Date,amount:number)=>{const next=new Date(date);next.setDate(next.getDate()+amount);return next};
const dayDistance=(start:Date,end:Date)=>Math.round((Date.UTC(end.getFullYear(),end.getMonth(),end.getDate())-Date.UTC(start.getFullYear(),start.getMonth(),start.getDate()))/dayMs);
export type TimelineWindow={startKey:string;dayCount:number;weekCount:number};
export type TimelinePlacement={kind:"unscheduled"|"milestone"|"range";left:number;width:number;marker:"start"|"due"|"range"|"none";startKey?:string;endKey?:string;needsReview?:boolean};
export type CalendarMarker={date:string;kind:"start"|"due"};
export function buildTimelineWindow(tasks:Pick<Task,"startDate"|"dueDate">[],bounds?:{startDate?:string;dueDate?:string},today=new Date()):TimelineWindow{const keys=[bounds?.startDate,bounds?.dueDate,...tasks.flatMap(task=>[task.startDate,task.dueDate])].filter(validDateKey) as string[];const earliest=keys.length?dateFromKey([...keys].sort()[0]??localDateKey(today)):new Date(today.getFullYear(),today.getMonth(),today.getDate());const latest=keys.length?dateFromKey([...keys].sort().at(-1)??localDateKey(today)):earliest;const start=new Date(earliest);const mondayOffset=(start.getDay()+6)%7;start.setDate(start.getDate()-mondayOffset);const minimumEnd=addLocalDays(start,41);const targetEnd=latest>minimumEnd?latest:minimumEnd;const weekCount=Math.max(6,Math.ceil((dayDistance(start,targetEnd)+1)/7));return {startKey:localDateKey(start),dayCount:weekCount*7,weekCount}}
export function timelinePlacement(task:Pick<Task,"startDate"|"dueDate">,window:TimelineWindow):TimelinePlacement{const hasStart=validDateKey(task.startDate),hasDue=validDateKey(task.dueDate);if(!hasStart&&!hasDue)return {kind:"unscheduled",left:0,width:0,marker:"none"};const windowStart=dateFromKey(window.startKey);if(hasStart&&hasDue&&task.startDate!==task.dueDate){let startKey=task.startDate,endKey=task.dueDate,needsReview=false;if(endKey<startKey){[startKey,endKey]=[endKey,startKey];needsReview=true}const startOffset=dayDistance(windowStart,dateFromKey(startKey)),endOffset=dayDistance(windowStart,dateFromKey(endKey));return {kind:"range",left:startOffset/window.dayCount*100,width:Math.max(1,(endOffset-startOffset+1)/window.dayCount*100),marker:"range",startKey,endKey,needsReview}}const key=hasDue?task.dueDate:task.startDate;const offset=dayDistance(windowStart,dateFromKey(key));return {kind:"milestone",left:(offset+.5)/window.dayCount*100,width:0,marker:hasDue?"due":"start",startKey:key,endKey:key}}
export function calendarMarkers(task:Pick<Task,"startDate"|"dueDate">):CalendarMarker[]{const hasStart=validDateKey(task.startDate),hasDue=validDateKey(task.dueDate);if(hasDue&&task.startDate===task.dueDate)return [{date:task.dueDate,kind:"due"}];const markers:CalendarMarker[]=[];if(hasStart)markers.push({date:task.startDate,kind:"start"});if(hasDue)markers.push({date:task.dueDate,kind:"due"});return markers}

export type MarkdownBlock={type:"heading"|"paragraph"|"unordered-list"|"ordered-list"|"quote"|"code"|"rule";text?:string;items?:string[];level?:number};
export function parseMarkdown(content:string):MarkdownBlock[]{const lines=content.replace(/\r\n?/g,"\n").split("\n"),blocks:MarkdownBlock[]=[];let index=0;const startsBlock=(line:string)=>!line.trim()||/^(```|#{1,3}\s|[-*]\s|\d+\.\s|>\s?|---+$)/.test(line.trim());while(index<lines.length){const raw=lines[index]??"",line=raw.trim();if(!line){index++;continue}if(line.startsWith("```")){const code:string[]=[];index++;while(index<lines.length&&!(lines[index]??"").trim().startsWith("```")){code.push(lines[index]??"");index++}if(index<lines.length)index++;blocks.push({type:"code",text:code.join("\n")});continue}const heading=line.match(/^(#{1,3})\s+(.+)$/);if(heading){blocks.push({type:"heading",level:heading[1]?.length??1,text:heading[2]??""});index++;continue}if(/^---+$/.test(line)){blocks.push({type:"rule"});index++;continue}if(/^[-*]\s+/.test(line)){const items:string[]=[];while(index<lines.length&&/^[-*]\s+/.test((lines[index]??"").trim())){items.push((lines[index]??"").trim().replace(/^[-*]\s+/,""));index++}blocks.push({type:"unordered-list",items});continue}if(/^\d+\.\s+/.test(line)){const items:string[]=[];while(index<lines.length&&/^\d+\.\s+/.test((lines[index]??"").trim())){items.push((lines[index]??"").trim().replace(/^\d+\.\s+/,""));index++}blocks.push({type:"ordered-list",items});continue}if(line.startsWith(">")){const quote:string[]=[];while(index<lines.length&&(lines[index]??"").trim().startsWith(">")){quote.push((lines[index]??"").trim().replace(/^>\s?/,""));index++}blocks.push({type:"quote",text:quote.join(" ")});continue}const paragraph=[line];index++;while(index<lines.length&&!startsBlock(lines[index]??"")){paragraph.push((lines[index]??"").trim());index++}blocks.push({type:"paragraph",text:paragraph.join(" ")})}return blocks}
