import type { Task, TimeEntry } from "./types";
export const minutesLabel=(minutes:number)=>minutes<60?`${minutes}m`:`${Math.floor(minutes/60)}h ${minutes%60?`${minutes%60}m`:""}`.trim();
export const secondsLabel=(seconds:number)=>{const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60),s=Math.max(0,Math.floor(seconds%60));return h?`${h}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`:`${m}:${String(s).padStart(2,"0")}`};
export function taskSeconds(taskId:string,entries:TimeEntry[],now=Date.now()){return entries.filter(e=>e.taskId===taskId).reduce((sum,e)=>sum+(e.stoppedAt?e.durationSeconds:Math.max(0,Math.floor((now-new Date(e.startedAt).getTime())/1000))),0)}
export const dueTone=(task:Task,now=new Date())=>{if(task.status==="done"||!task.dueDate)return "neutral";const days=(new Date(`${task.dueDate}T23:59:59`).getTime()-now.getTime())/86400000;return days<0?"overdue":days<3?"soon":"neutral"};
export function monthGrid(anchor:Date){const first=new Date(anchor.getFullYear(),anchor.getMonth(),1),start=new Date(first);start.setDate(first.getDate()-first.getDay());return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})}

export type MarkdownBlock={type:"heading"|"paragraph"|"unordered-list"|"ordered-list"|"quote"|"code"|"rule";text?:string;items?:string[];level?:number};
export function parseMarkdown(content:string):MarkdownBlock[]{const lines=content.replace(/\r\n?/g,"\n").split("\n"),blocks:MarkdownBlock[]=[];let index=0;const startsBlock=(line:string)=>!line.trim()||/^(```|#{1,3}\s|[-*]\s|\d+\.\s|>\s?|---+$)/.test(line.trim());while(index<lines.length){const raw=lines[index]??"",line=raw.trim();if(!line){index++;continue}if(line.startsWith("```")){const code:string[]=[];index++;while(index<lines.length&&!(lines[index]??"").trim().startsWith("```")){code.push(lines[index]??"");index++}if(index<lines.length)index++;blocks.push({type:"code",text:code.join("\n")});continue}const heading=line.match(/^(#{1,3})\s+(.+)$/);if(heading){blocks.push({type:"heading",level:heading[1]?.length??1,text:heading[2]??""});index++;continue}if(/^---+$/.test(line)){blocks.push({type:"rule"});index++;continue}if(/^[-*]\s+/.test(line)){const items:string[]=[];while(index<lines.length&&/^[-*]\s+/.test((lines[index]??"").trim())){items.push((lines[index]??"").trim().replace(/^[-*]\s+/,""));index++}blocks.push({type:"unordered-list",items});continue}if(/^\d+\.\s+/.test(line)){const items:string[]=[];while(index<lines.length&&/^\d+\.\s+/.test((lines[index]??"").trim())){items.push((lines[index]??"").trim().replace(/^\d+\.\s+/,""));index++}blocks.push({type:"ordered-list",items});continue}if(line.startsWith(">")){const quote:string[]=[];while(index<lines.length&&(lines[index]??"").trim().startsWith(">")){quote.push((lines[index]??"").trim().replace(/^>\s?/,""));index++}blocks.push({type:"quote",text:quote.join(" ")});continue}const paragraph=[line];index++;while(index<lines.length&&!startsBlock(lines[index]??"")){paragraph.push((lines[index]??"").trim());index++}blocks.push({type:"paragraph",text:paragraph.join(" ")})}return blocks}
