import { chromium } from '../frontend/node_modules/playwright-core/index.mjs';
import fs from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const password=process.env.TEMPO_QA_PASSWORD??(process.env.TEMPO_QA_PASSWORD_FILE?String(await fs.readFile(process.env.TEMPO_QA_PASSWORD_FILE)).trim():"");if(!password)throw new Error('TEMPO_QA_PASSWORD or TEMPO_QA_PASSWORD_FILE is required');
const baseURL=process.env.TEMPO_QA_URL??'http://127.0.0.1:4190';
const out=fileURLToPath(new URL('.',import.meta.url));await fs.mkdir(out,{recursive:true});
const browserArgs=['--no-sandbox'];if(process.env.TEMPO_QA_HOST_MAP)browserArgs.push(`--host-resolver-rules=${process.env.TEMPO_QA_HOST_MAP}`);
const browser=await chromium.launch({headless:true,executablePath:process.env.TEMPO_CHROMIUM??'/usr/bin/chromium',args:browserArgs});
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.goto(baseURL,{waitUntil:'networkidle'});
await page.getByRole('heading',{name:'Sign in to your workspace'}).waitFor();
await page.screenshot({path:`${out}/desktop-login.png`,fullPage:true});
await page.getByLabel('Password').fill('deliberately-wrong');await page.getByRole('button',{name:'Sign in'}).click();await page.getByRole('alert').waitFor();errors.length=0;
await page.getByLabel('Password').fill(password);await page.getByRole('button',{name:'Sign in'}).click();
await page.locator('.project-title').filter({hasText:'Product launch'}).waitFor();
await page.screenshot({path:`${out}/desktop-overview.png`,fullPage:true});
const desktopDock=page.getByRole('group',{name:'Quick actions'});await desktopDock.waitFor();
await desktopDock.getByRole('button',{name:'New task'}).click();
await page.getByLabel('Task title').fill('Approve launch checklist');
await page.getByLabel('Description').fill('Final owner sign-off before release.');
await page.getByLabel('Assignee').fill('Otty');
await page.getByLabel('Due date').fill('2026-08-02');
await page.getByLabel('Tags').fill('launch, approval');
await page.getByRole('button',{name:'Create task'}).click();
await page.locator('.nav-list button').nth(1).click();
await page.getByText('Approve launch checklist',{exact:true}).waitFor();
const createdCard=page.locator('.task-card',{hasText:'Approve launch checklist'}),progressColumn=page.locator('[data-kanban-status="progress"]'),reviewColumn=page.locator('[data-kanban-status="review"]'),doneColumn=page.locator('[data-kanban-status="done"]');
await createdCard.dragTo(progressColumn);
await progressColumn.getByText('Approve launch checklist',{exact:true}).waitFor();
let movedStatus=await page.evaluate(async()=>{const state=await fetch('/api/state').then(r=>r.json());return state.tasks.find(t=>t.title==='Approve launch checklist')?.status});if(movedStatus!=='progress')throw new Error(`HTML drag did not persist: ${movedStatus}`);
await progressColumn.getByRole('button',{name:'Drag Approve launch checklist'}).press('ArrowRight');
await reviewColumn.getByText('Approve launch checklist',{exact:true}).waitFor();
movedStatus=await page.evaluate(async()=>{const state=await fetch('/api/state').then(r=>r.json());return state.tasks.find(t=>t.title==='Approve launch checklist')?.status});if(movedStatus!=='review')throw new Error(`keyboard move did not persist: ${movedStatus}`);
const dragHandle=reviewColumn.getByRole('button',{name:'Drag Approve launch checklist'}),handleBox=await dragHandle.boundingBox(),doneBox=await doneColumn.boundingBox();if(!handleBox||!doneBox)throw new Error('pointer drag geometry unavailable');
await page.mouse.move(handleBox.x+handleBox.width/2,handleBox.y+handleBox.height/2);await page.mouse.down();await page.mouse.move(doneBox.x+doneBox.width/2,doneBox.y+120,{steps:12});await page.mouse.up();
await doneColumn.getByText('Approve launch checklist',{exact:true}).waitFor();
movedStatus=await page.evaluate(async()=>{const state=await fetch('/api/state').then(r=>r.json());return state.tasks.find(t=>t.title==='Approve launch checklist')?.status});if(movedStatus!=='done')throw new Error(`pointer move did not persist: ${movedStatus}`);
await page.screenshot({path:`${out}/desktop-kanban.png`,fullPage:true});
await page.locator('.nav-list button').nth(5).click();
const play=page.locator('.time-row button').first();await play.click();await page.getByText('TRACKING NOW',{exact:true}).waitFor();
await page.waitForTimeout(1200);await page.getByRole('button',{name:'Stop timer'}).click();
await page.getByText('FOCUS TIMER',{exact:true}).waitFor();
await page.screenshot({path:`${out}/desktop-time.png`,fullPage:true});
await page.getByRole('button',{name:'Select workspace'}).click();
await page.getByRole('menuitem',{name:'Add new workspace'}).click();
await page.getByLabel('Workspace name').fill('Client Operations');
await page.getByRole('button',{name:'Create workspace'}).click();
await page.getByRole('button',{name:'Select workspace'}).click();
await page.getByRole('menuitemradio',{name:'Client Operations'}).click();
if(await page.locator('.project-list').getByText('Product launch',{exact:true}).count())throw new Error('workspace project isolation failed');
await page.getByRole('button',{name:'Select workspace'}).click();
await page.getByRole('menuitemradio',{name:'Default workspace'}).click();
await page.getByText('Product launch',{exact:true}).first().waitFor();
const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});mobile.on('pageerror',e=>errors.push(`mobile: ${e.message}`));
await mobile.goto(baseURL,{waitUntil:'networkidle'});await mobile.getByRole('heading',{name:'Sign in to your workspace'}).waitFor();
await mobile.screenshot({path:`${out}/mobile-login.png`,fullPage:true});await mobile.getByLabel('Password').fill(password);await mobile.getByRole('button',{name:'Sign in'}).click();await mobile.locator('.project-title').filter({hasText:'Product launch'}).waitFor();
const mobileDock=mobile.getByRole('group',{name:'Quick actions'});await mobileDock.waitFor();if(!await mobileDock.getByRole('button',{name:'Account settings'}).isVisible())throw new Error('mobile settings action is hidden');
await mobile.getByRole('button',{name:'Open navigation'}).click();await mobile.screenshot({path:`${out}/mobile-navigation.png`,fullPage:true});
await mobile.locator('.nav-list button').nth(4).click();await mobile.locator('.calendar-view h2').waitFor();await mobile.waitForTimeout(250);
await mobile.screenshot({path:`${out}/mobile-calendar.png`,fullPage:true});
const state=await page.evaluate(async()=>{const response=await fetch('/api/state');if(!response.ok)throw new Error(`state request failed: ${response.status}`);return response.json()});
await page.getByRole('button',{name:'Log out'}).click();await page.getByRole('heading',{name:'Sign in to your workspace'}).waitFor();
console.log(JSON.stringify({desktopTitle:await page.title(),createdTask:state.tasks.some(t=>t.title==='Approve launch checklist'),runningTimers:state.timeEntries.filter(e=>!e.stoppedAt).length,workspaces:state.workspaces.length,screenshots:7,logoutReturnedToLogin:true,errors},null,2));
await browser.close();if(errors.length)process.exitCode=1;
